// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace HCMISCodedUITest.LoginUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v14_1;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class LoginUIMap
    {
        
        /// <summary>
        /// This tires to login
        /// </summary>
        public void LoginTest()
        {
            #region Variable Declarations
            DXBaseLayoutItem uIDatabaseIdentityLayoutControlItem = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UIDatabaseIdentityLayoutControlItem;
            DXTextEdit uITxtUsernameEdit = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UITxtUsernameitemLayoutControlItem.UITxtUsernameEdit;
            #endregion

            // Click 'DatabaseIdentity' LayoutControlItem
            Mouse.Click(uIDatabaseIdentityLayoutControlItem, new Point(206, 30));

            // Type 'getahun' in 'txtUsername' text box
            //ValueAsString
            uITxtUsernameEdit.ValueAsString = this.LoginTestParams.UITxtUsernameEditValueAsString;

            // Type 'Control + {LMenu}' in 'txtUsername' text box
            Keyboard.SendKeys(uITxtUsernameEdit, this.LoginTestParams.UITxtUsernameEditSendKeys, ModifierKeys.Control);
        }
        
        /// <summary>
        /// LoadVersion - Use 'LoadVersionParams' to pass parameters into this method.
        /// </summary>
        public void LoadVersion()
        {
            #region Variable Declarations
            DXTextEdit uITxtUsernameEdit = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UITxtUsernameitemLayoutControlItem.UITxtUsernameEdit;
            DXBaseLayoutItem uIVersionLabelLayoutControlItem = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UIVersionLabelLayoutControlItem;
            #endregion

            // Type 'getahun' in 'txtUsername' text box
            //ValueAsString
            uITxtUsernameEdit.ValueAsString = this.LoadVersionParams.UITxtUsernameEditValueAsString;

            // Click 'VersionLabel' LayoutControlItem while pressing Shift
            Mouse.Click(uIVersionLabelLayoutControlItem, MouseButtons.Left, ModifierKeys.Shift, new Point(469, 8));

            // Double-Click 'VersionLabel' LayoutControlItem while pressing Shift
            Mouse.DoubleClick(uIVersionLabelLayoutControlItem, MouseButtons.Left, ModifierKeys.Shift, new Point(469, 8));

            // Click 'VersionLabel' LayoutControlItem while pressing Shift
            Mouse.Click(uIVersionLabelLayoutControlItem, MouseButtons.Left, ModifierKeys.Shift, new Point(469, 8));
        }
        
        /// <summary>
        /// this loads the app version
        /// </summary>
        public string LoadAppVersion()
        {
            #region Variable Declarations
            DXBaseLayoutItem uIVersionLabelLayoutControlItem = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UIVersionLabelLayoutControlItem;
            #endregion

            // Double-Click 'VersionLabel' LayoutControlItem while pressing Control
            Mouse.DoubleClick(uIVersionLabelLayoutControlItem, MouseButtons.Left, ModifierKeys.Control, new Point(459, 7));

            // Double-Click 'VersionLabel' LayoutControlItem while pressing Control
            Mouse.DoubleClick(uIVersionLabelLayoutControlItem, MouseButtons.Left, ModifierKeys.Control, new Point(459, 7));
            return "fake";
        }
        
        /// <summary>
        /// asdf
        /// </summary>
        public void press_login()
        {
            #region Variable Declarations
            DXButton uILoginButton = this.UIHCMISWarehouseWindow.UILoginFormConvertedLaCustom.UIRootLayoutGroup.UIXpButton18itemLayoutControlItem.UILoginButton;
            #endregion

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(1, 1));
        }
        
        #region Properties
        public virtual LoginTestParams LoginTestParams
        {
            get
            {
                if ((this.mLoginTestParams == null))
                {
                    this.mLoginTestParams = new LoginTestParams();
                }
                return this.mLoginTestParams;
            }
        }
        
        public virtual LoadVersionParams LoadVersionParams
        {
            get
            {
                if ((this.mLoadVersionParams == null))
                {
                    this.mLoadVersionParams = new LoadVersionParams();
                }
                return this.mLoadVersionParams;
            }
        }
        
        public UIKdiff3Window UIKdiff3Window
        {
            get
            {
                if ((this.mUIKdiff3Window == null))
                {
                    this.mUIKdiff3Window = new UIKdiff3Window();
                }
                return this.mUIKdiff3Window;
            }
        }
        
        public UIHCMISWarehouseWindow UIHCMISWarehouseWindow
        {
            get
            {
                if ((this.mUIHCMISWarehouseWindow == null))
                {
                    this.mUIHCMISWarehouseWindow = new UIHCMISWarehouseWindow();
                }
                return this.mUIHCMISWarehouseWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginTestParams mLoginTestParams;
        
        private LoadVersionParams mLoadVersionParams;
        
        private UIKdiff3Window mUIKdiff3Window;
        
        private UIHCMISWarehouseWindow mUIHCMISWarehouseWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class LoginTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'getahun' in 'txtUsername' text box
        /// </summary>
        public string UITxtUsernameEditValueAsString = "getahun";
        
        /// <summary>
        /// Type 'Control + {LMenu}' in 'txtUsername' text box
        /// </summary>
        public string UITxtUsernameEditSendKeys = "{LMenu}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoadVersion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class LoadVersionParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'getahun' in 'txtUsername' text box
        /// </summary>
        public string UITxtUsernameEditValueAsString = "getahun";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIKdiff3Window : WinWindow
    {
        
        public UIKdiff3Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "kdiff3";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            this.WindowTitles.Add("kdiff3");
            #endregion
        }
        
        #region Properties
        public UIFolderViewWindow UIFolderViewWindow
        {
            get
            {
                if ((this.mUIFolderViewWindow == null))
                {
                    this.mUIFolderViewWindow = new UIFolderViewWindow(this);
                }
                return this.mUIFolderViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFolderViewWindow mUIFolderViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFolderViewWindow : WinWindow
    {
        
        public UIFolderViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("kdiff3");
            #endregion
        }
        
        #region Properties
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("kdiff3");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHCMISWarehouseWindow : DXWindow
    {
        
        public UIHCMISWarehouseWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = " HCMIS Warehouse";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add(" HCMIS Warehouse");
            #endregion
        }
        
        #region Properties
        public UILoginFormConvertedLaCustom UILoginFormConvertedLaCustom
        {
            get
            {
                if ((this.mUILoginFormConvertedLaCustom == null))
                {
                    this.mUILoginFormConvertedLaCustom = new UILoginFormConvertedLaCustom(this);
                }
                return this.mUILoginFormConvertedLaCustom;
            }
        }
        #endregion
        
        #region Fields
        private UILoginFormConvertedLaCustom mUILoginFormConvertedLaCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILoginFormConvertedLaCustom : DXTestControl
    {
        
        public UILoginFormConvertedLaCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "LoginFormConvertedLayout";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControl";
            this.WindowTitles.Add(" HCMIS Warehouse");
            #endregion
        }
        
        #region Properties
        public UIRootLayoutGroup UIRootLayoutGroup
        {
            get
            {
                if ((this.mUIRootLayoutGroup == null))
                {
                    this.mUIRootLayoutGroup = new UIRootLayoutGroup(this);
                }
                return this.mUIRootLayoutGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIRootLayoutGroup mUIRootLayoutGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIRootLayoutGroup : DXBaseLayoutItem
    {
        
        public UIRootLayoutGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "Root";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutGroup";
            this.WindowTitles.Add(" HCMIS Warehouse");
            #endregion
        }
        
        #region Properties
        public DXBaseLayoutItem UIDatabaseIdentityLayoutControlItem
        {
            get
            {
                if ((this.mUIDatabaseIdentityLayoutControlItem == null))
                {
                    this.mUIDatabaseIdentityLayoutControlItem = new DXBaseLayoutItem(this);
                    #region Search Criteria
                    this.mUIDatabaseIdentityLayoutControlItem.SearchProperties[DXTestControl.PropertyNames.Name] = "DatabaseIdentity";
                    this.mUIDatabaseIdentityLayoutControlItem.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControlItem";
                    this.mUIDatabaseIdentityLayoutControlItem.WindowTitles.Add(" HCMIS Warehouse");
                    #endregion
                }
                return this.mUIDatabaseIdentityLayoutControlItem;
            }
        }
        
        public UITxtUsernameitemLayoutControlItem UITxtUsernameitemLayoutControlItem
        {
            get
            {
                if ((this.mUITxtUsernameitemLayoutControlItem == null))
                {
                    this.mUITxtUsernameitemLayoutControlItem = new UITxtUsernameitemLayoutControlItem(this);
                }
                return this.mUITxtUsernameitemLayoutControlItem;
            }
        }
        
        public DXBaseLayoutItem UIVersionLabelLayoutControlItem
        {
            get
            {
                if ((this.mUIVersionLabelLayoutControlItem == null))
                {
                    this.mUIVersionLabelLayoutControlItem = new DXBaseLayoutItem(this);
                    #region Search Criteria
                    this.mUIVersionLabelLayoutControlItem.SearchProperties[DXTestControl.PropertyNames.Name] = "VersionLabel";
                    this.mUIVersionLabelLayoutControlItem.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControlItem";
                    this.mUIVersionLabelLayoutControlItem.WindowTitles.Add(" HCMIS Warehouse");
                    #endregion
                }
                return this.mUIVersionLabelLayoutControlItem;
            }
        }
        
        public UIXpButton18itemLayoutControlItem UIXpButton18itemLayoutControlItem
        {
            get
            {
                if ((this.mUIXpButton18itemLayoutControlItem == null))
                {
                    this.mUIXpButton18itemLayoutControlItem = new UIXpButton18itemLayoutControlItem(this);
                }
                return this.mUIXpButton18itemLayoutControlItem;
            }
        }
        #endregion
        
        #region Fields
        private DXBaseLayoutItem mUIDatabaseIdentityLayoutControlItem;
        
        private UITxtUsernameitemLayoutControlItem mUITxtUsernameitemLayoutControlItem;
        
        private DXBaseLayoutItem mUIVersionLabelLayoutControlItem;
        
        private UIXpButton18itemLayoutControlItem mUIXpButton18itemLayoutControlItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtUsernameitemLayoutControlItem : DXBaseLayoutItem
    {
        
        public UITxtUsernameitemLayoutControlItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "txtUsernameitem";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControlItem";
            this.WindowTitles.Add(" HCMIS Warehouse");
            #endregion
        }
        
        #region Properties
        public DXTextEdit UITxtUsernameEdit
        {
            get
            {
                if ((this.mUITxtUsernameEdit == null))
                {
                    this.mUITxtUsernameEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtUsernameEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtUsername";
                    this.mUITxtUsernameEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtUsernameEdit.WindowTitles.Add(" HCMIS Warehouse");
                    #endregion
                }
                return this.mUITxtUsernameEdit;
            }
        }
        #endregion
        
        #region Fields
        private DXTextEdit mUITxtUsernameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIXpButton18itemLayoutControlItem : DXBaseLayoutItem
    {
        
        public UIXpButton18itemLayoutControlItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "xpButton18item";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControlItem";
            this.WindowTitles.Add(" HCMIS Warehouse");
            #endregion
        }
        
        #region Properties
        public DXButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new DXButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[DXTestControl.PropertyNames.Name] = "xpButton18";
                    this.mUILoginButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUILoginButton.WindowTitles.Add(" HCMIS Warehouse");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUILoginButton;
        #endregion
    }
}
